version: '3.8'

services:
  # -----------------------------------------------------
  #  Banco de Dados do User Service
  # -----------------------------------------------------
  user-db:
    image: postgres:16-alpine
    container_name: shopflow-user-db
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: user_pass
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  # -----------------------------------------------------
  #  Banco de Dados do Product Service (MongoDB)
  # -----------------------------------------------------
  product-mongodb:
    image: mongo:7.0
    container_name: shopflow-product-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: product_admin
      MONGO_INITDB_ROOT_PASSWORD: product_pass
    ports:
      - "27017:27017"
    volumes:
      - product-mongodb-data:/data/db
    restart: unless-stopped
    # -----------------------------------------------------
    # Banco de Dados do Order Service
    # -----------------------------------------------------
  order-db:
    image: postgres:16-alpine
    container_name: shopflow-order-db
    environment:
      POSTGRES_USER: order_admin
      POSTGRES_PASSWORD: order_pass
      POSTGRES_DB: order_db
    ports:
      - "5435:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  # -----------------------------------------------------
  # AWS Mock (LocalStack) para SNS/SQS
  # -----------------------------------------------------
  localstack:
    image: localstack/localstack:3.4.0
    container_name: shopflow-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,sqs
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
    restart: unless-stopped

  # -----------------------------------------------------
  # Banco de Dados do Payment Service
  # -----------------------------------------------------
  payment-db:
    image: postgres:16-alpine
    container_name: shopflow-payment-db
    environment:
      POSTGRES_USER: payment_admin
      POSTGRES_PASSWORD: payment_pass
      POSTGRES_DB: payment_db
    ports:
      - "5436:5432"
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  # -----------------------------------------------------
  # Banco de Dados do Cart Service
  # -----------------------------------------------------
  cart-db:
    image: postgres:16-alpine
    container_name: shopflow-cart-db
    environment:
      POSTGRES_USER: cart_admin
      POSTGRES_PASSWORD: cart_pass
      POSTGRES_DB: cart_db
    ports:
      - "5437:5432"
    volumes:
      - cart-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  # -----------------------------------------------------
  # Banco de Dados do Inventory Service
  # -----------------------------------------------------
  inventory-db:
    image: postgres:16-alpine
    container_name: shopflow-inventory-db
    environment:
      POSTGRES_USER: inventory_admin
      POSTGRES_PASSWORD: inventory_pass
      POSTGRES_DB: inventory_db
    ports:
      - "5438:5432"
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  # -----------------------------------------------------
  # Banco de Dados do Notification Service
  # -----------------------------------------------------
  notification-db:
    image: postgres:16-alpine
    container_name: shopflow-notification-db
    environment:
      POSTGRES_USER: notification_admin
      POSTGRES_PASSWORD: notification_pass
      POSTGRES_DB: notification_db
    ports:
      - "5439:5432"
    volumes:
      - notification-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  # -----------------------------------------------------
  # Redis Cache (Product Service)
  # -----------------------------------------------------
  redis:
    image: redis:7-alpine
    container_name: shopflow-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres-data:
  user-db-data:
  product-mongodb-data:
  order-db-data:
  payment-db-data:
  cart-db-data:
  inventory-db-data:
  notification-db-data:
