server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/payment_db
    username: payment_admin
    password: payment_pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  cloud:
    aws:
      credentials:
        access-key: dummy
        secret-key: dummy
      region:
        static: us-east-1
      sqs:
        endpoint: http://localhost:4566
