spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/order_db
    username: order_admin
    password: order_pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  cloud:
    aws:
      credentials:
        access-key: dummy
        secret-key: dummy
      region:
        static: us-east-1
      sns:
        endpoint: http://localhost:4566

server:
  port: 8082
