spring.application.name=product-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5434/product_db
spring.datasource.username=product_admin
spring.datasource.password=product_pass

spring.jpa.hibernate.ddl-auto=validate
