spring.application.name=product-service
server.port=8081

spring.data.mongodb.uri=mongodb://product_admin:product_pass@localhost:27017/shopflow_product?authSource=admin

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
