server:
  port: 8084

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5437/cart_db
    username: cart_admin
    password: cart_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5437/cart_db
    user: cart_admin
    password: cart_pass
